### ISSUE TITLE
Remix documentation severely lacking

### ISSUE THREAD

**Issue by WesleyYue** [clerkinc/remix-auth-starter#6]
Incorporating Clerk into Remix has been super frustrating, as far as I can tell, the docs and this repo is completely outdated and not caught up to all the breaking changes in the latest @clerk/remix package. Please let me know if I'm mistaken, but honestly have been pretty disappointed at our experience implementing Clerk when it's supposed to be designed for developers

Here are all the things I see that are wrong:
- This section in the docs makes it seem like you can retrieve `user` from getAuth() as long as you turn on loadUser = true, and the return type of getAuth also suggests it should be possible to do so, but as far as I can tell, this is totally wrong. The only hint I had of this after hours of debugging was checking this [link](https://clerk.dev/docs/upgrade-guides/upgrade-remix-from-1.x-to-2.x), which was hidden away in that page. It seems from that page, the only three valid things that can be returned from getAuth are: userId, sessionId, getToken
![image](https://user-images.githubusercontent.com/5280818/216896301-07300af2-3edb-4d1e-ba51-0be3258566ad.png)
- Data fetching is importing from `experimental`. Additional source of confusion – am I supposed to be using this? Is it unstable? Why is it the only way to perform an action in a major stable release?
![image](https://user-images.githubusercontent.com/5280818/216896821-f6b5e1dc-f549-4c76-b211-c67de9ddf34b.png)
- In the breaking changes page, it says you can't do `import { users } from "@clerk/remix/api.server";` anymore in 2.x, but this repo, which is using 2.x, does use that import? https://github.com/clerkinc/remix-auth-starter/blob/main/app/routes/ssr-user-demo.tsx#L6
![image](https://user-images.githubusercontent.com/5280818/216896967-0073739b-148d-44ff-a189-4c98fd127937.png)

Am I the only one running into these issues?

**Comment by Scott-Fischer** [comment]
> Am I the only one running into these issues?

No you are not - I completely agree!

I just spent the last several hours trying to get Clerk to work with supabase RLS + SSR for an MVP project and my only conclusion is that I'm strongly reconsidering using Clerk. Which is sad because I was 100% sold on the promise that Clerk is making.

If the idea is to cater to developers, then I strongly suggest the clerk team either updates their example repos or archives them. Nothing frustrates us more than a SaaS product that promises to make things easier but actually ends up wasting time. 

Neither this example or the https://github.com/clerkinc/remix-bossa-nova-stack starter template use the latest release of Clerk's remix package and that's a problem.

**Comment by SokratisVidros** [comment]
Thank you both for bringing this to our attention. Clerk is operating, by definition, in a fast-changing environment. Keeping up to date with all framework changes and applying them to our starter repos is challenging. For now, I advise using our official starter guides in our [docs](https://clerk.dev/docs). If you face further integration issues while using Clerk, please [talk to us](https://clerk.dev/support).
